### ISSUE TITLE
Package for Conda?

### ISSUE THREAD

**Issue by mefuller** [bryanwweber/CanSen#46]
Could this be packaged for conda (please)?

**Comment by bryanwweber** [comment]
It is, `conda install -c bryanwweber cansen`

**Comment by mefuller** [comment]
Thanks! I couldn't find that in the documentation

**Comment by bryanwweber** [comment]
Yep, that would make it hard to figure out how to do it! I think it's not documented because I set it up before Cantera was available as a conda package. I'll leave this open as a "to-do" to document this.

**Comment by mefuller** [comment]
Thanks.
FYI, I installed it manually as the current package has a dependency of python 3.4.* to 3.6.*, so I would like to request that compatibility with higher versions be checked / added

**Comment by bryanwweber** [comment]
Yeah, it should really be a `noarch` package, but last time I built the conda package, I appear to have done so manually, before I learned about `noarch` packages. If you want, you can add a GitHub Actions workflow to build the conda package. This isn't very high on my priority list, unfortunately, so it will be a while till I can get to it. Especially because I'm pretty sure nearly this whole package should be rewritten to comport with more modern Cantera :joy:
